import { Router, Response } from 'express';
import { User, Zainbox } from '../models';
import { authenticate, AuthenticatedRequest } from '../middleware';
import { zainpayService } from '../services/ZainpayService';

const router = Router();

// All routes require authentication
router.use(authenticate);

/**
 * Create a new Zainbox
 * POST /api/zainbox
 */
router.post('/', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
    try {
        const userId = req.user!.id;
        const { name, emailNotification, tags, callbackUrl } = req.body;

        if (!name || !emailNotification || !tags || !callbackUrl) {
            res.status(400).json({
                success: false,
                message: 'Missing required fields: name, emailNotification, tags, callbackUrl',
            });
            return;
        }

        // Call Zainpay API to create Zainbox
        const zainpayResponse = await zainpayService.createZainbox({
            name,
            emailNotification,
            tags,
            callbackUrl,
        });

        if (zainpayResponse.code !== '00' || !zainpayResponse.data) {
            res.status(400).json({
                success: false,
                message: zainpayResponse.description || 'Failed to create Zainbox on Zainpay',
            });
            return;
        }

        // Zainpay returns an array of Zainboxes, we assume the last one is the created one or we filter by name?
        // Actually the response data is Zainbox[], let's assume it returns the created one or all.
        // Based on Zainpay docs (implied), it might return the created object.
        // But the type says Zainbox[]. Let's check the service implementation again.
        // Service: Promise<ZainpayResponse<Zainbox[]>>

        // We need to find the one we just created.
        // For now, let's assume the API returns the created zainbox in the list.
        // We can match by codeName (which is generated by Zainpay?) or name.

        // Wait, Zainpay create request payload doesn't include codeName?
        // Payload: { name, emailNotification, tags, callbackUrl }
        // Response: Zainbox[]

        // Let's assume the last one is the new one, or we filter by name.
        const createdZainboxData = zainpayResponse.data.find(z => z.name === name); // Simple matching

        if (!createdZainboxData) {
            res.status(500).json({
                success: false,
                message: 'Zainbox created but not found in response',
            });
            return;
        }

        // Save to local DB
        const zainbox = new Zainbox({
            userId,
            name: createdZainboxData.name,
            emailNotification: createdZainboxData.emailNotification,
            tags: createdZainboxData.tags,
            callbackUrl: createdZainboxData.callbackUrl,
            codeName: createdZainboxData.codeName,
            zainboxCode: createdZainboxData.zainboxCode,
            isLive: createdZainboxData.isLive,
        });

        await zainbox.save();

        res.status(201).json({
            success: true,
            message: 'Zainbox created successfully',
            data: zainbox,
        });

    } catch (error: any) {
        console.error('Create Zainbox error:', error);
        res.status(500).json({
            success: false,
            message: error.message || 'Failed to create Zainbox',
        });
    }
});

/**
 * List all Zainboxes for the user
 * GET /api/zainbox
 */
router.get('/', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
    try {
        const userId = req.user!.id;
        const zainboxes = await Zainbox.find({ userId });

        res.json({
            success: true,
            data: zainboxes,
        });
    } catch (error) {
        console.error('List Zainboxes error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to list Zainboxes',
        });
    }
});

/**
 * Get Zainbox Profile (Sync with Zainpay)
 * GET /api/zainbox/:zainboxCode
 */
router.get('/:zainboxCode', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
    try {
        const userId = req.user!.id;
        const { zainboxCode } = req.params;

        const zainbox = await Zainbox.findOne({ userId, zainboxCode });

        if (!zainbox) {
            res.status(404).json({
                success: false,
                message: 'Zainbox not found',
            });
            return;
        }

        // Fetch latest profile from Zainpay
        const profileResponse = await zainpayService.getZainboxProfile(zainboxCode);

        if (profileResponse.code === '00' && profileResponse.data) {
            // Update local DB if needed
            // For now just return the combined data
            res.json({
                success: true,
                data: {
                    local: zainbox,
                    remote: profileResponse.data
                }
            });
        } else {
            res.json({
                success: true,
                message: 'Local data retrieved, failed to fetch remote profile',
                data: {
                    local: zainbox,
                    remote: null
                }
            });
        }

    } catch (error) {
        console.error('Get Zainbox Profile error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to get Zainbox profile',
        });
    }
});

export default router;
